import type { BidState, PortfolioImpact } from "../types/bid";

export const portfolioImpactFixture: PortfolioImpact = {
  mode: "SIMULATION_ONLY",
  synthetic: true,
  trigger: {
    stable_key: "R17",
    change_summary: "Minimum count 3 → 4",
  },
  summary:
    "Recovering R17 creates a shared-personnel conflict between this tender and an overlapping delivery commitment.",
  before_state: "RECOVERABLE",
  after_state: "BLOCKED",
  assumptions: [
    "The companion delivery commitment and service windows are synthetic demo inputs.",
    "Potential capacity assumes Engineer D's CV and availability gaps are resolved.",
    "No employee is double-booked across overlapping delivery windows.",
    "No external delivery partner is assumed until its qualification and availability are verified.",
  ],
  capacity: {
    capability: "CISSP delivery personnel",
    unit: "concurrent CISSP assignments",
    proven_now: 3,
    potential_after_recovery: 4,
    concurrent_required: 5,
    shortfall: 1,
    window_start: "2026-10-01T00:00:00",
    window_end: "2026-12-01T00:00:00",
  },
  affected_bids: [
    {
      bid_id: "BID-DEMO-001",
      reference_number: "DGA/ICT/2026/017",
      title: "Managed Cybersecurity Monitoring and Response Services",
      relationship: "CURRENT",
      required_capacity: 4,
    },
    {
      bid_id: "BID-DEMO-SOC-008",
      reference_number: "DMA/SOC/2026/008",
      title: "Municipal SOC Operations Extension",
      relationship: "OTHER",
      required_capacity: 1,
    },
  ],
  routes: [
    {
      id: "protect-current-tender",
      action: "RECOVER",
      label: "Protect this tender",
      rationale:
        "Complete Engineer D's evidence and reserve all four potential CISSP personnel for the amended R17 obligation.",
      outcomes: [
        { bid_id: "BID-DEMO-001", status: "RECOVERABLE" },
        { bid_id: "BID-DEMO-SOC-008", status: "BLOCKED" },
      ],
      unresolved_facts: ["Engineer D's current CV", "Engineer D's availability"],
      requires_human_decision: true,
    },
    {
      id: "protect-existing-commitment",
      action: "WALK_AWAY",
      label: "Protect existing commitment",
      rationale:
        "Keep one CISSP assignment for the companion bid; only three potential slots remain for R17, so the amended tender cannot currently proceed.",
      outcomes: [
        { bid_id: "BID-DEMO-001", status: "BLOCKED" },
        { bid_id: "BID-DEMO-SOC-008", status: "FEASIBLE" },
      ],
      unresolved_facts: [],
      requires_human_decision: true,
    },
    {
      id: "verify-external-capacity",
      action: "PARTNER",
      label: "Verify external capacity",
      rationale:
        "Both bids may remain viable if one additional qualified delivery slot is verified before allocation.",
      outcomes: [
        { bid_id: "BID-DEMO-001", status: "UNCERTAIN" },
        { bid_id: "BID-DEMO-SOC-008", status: "FEASIBLE" },
      ],
      unresolved_facts: [
        "Partner qualification",
        "Partner availability",
        "Tender permission for the proposed delivery arrangement",
      ],
      requires_human_decision: true,
    },
  ],
  capability_roadmap: [
    {
      priority: 1,
      capability: "CISSP_DELIVERY_PERSONNEL",
      opportunity_ids: ["BID-DEMO-001", "BID-DEMO-SOC-008"],
      opportunities_affected: 2,
      requirement_count: 2,
      earliest_window_start: "2026-09-01T00:00:00",
      sources: ["Current R17 structured minimum_count", "Synthetic companion-bid staffing commitment"],
      gap_type: "ADDITIONAL_CAPACITY_REQUIRED",
      known_gap: 1,
      action: "Source 1 additional verified capability slot",
      effect: "Closes the hard concurrent-capacity shortfall in this scenario.",
      basis: "Calculated peak demand minus identified potential capacity.",
    },
    {
      priority: 2,
      capability: "CISSP_DELIVERY_PERSONNEL",
      opportunity_ids: ["BID-DEMO-001", "BID-DEMO-SOC-008"],
      opportunities_affected: 2,
      requirement_count: 2,
      earliest_window_start: "2026-09-01T00:00:00",
      sources: ["Current R17 structured minimum_count", "Synthetic companion-bid staffing commitment"],
      gap_type: "EVIDENCE_OR_AVAILABILITY",
      known_gap: 1,
      action: "Complete evidence and availability for 1 candidate",
      effect: "Converts identified potential capacity into proven delivery capacity.",
      basis:
        "Three complete R17 personnel evidence sets plus Engineer D as one identified candidate with unresolved CV and availability.",
    },
  ],
  calculation: {
    rule:
      "For each capability, sum mandatory demand across overlapping delivery windows. FEASIBLE fits proven capacity; RECOVERABLE fits only after potential capacity is verified; BLOCKED exceeds potential capacity; an unknown mandatory count is UNCERTAIN.",
    precedence: ["BLOCKED", "UNCERTAIN", "RECOVERABLE", "FEASIBLE"],
  },
  calculated_at: "2026-08-21T15:00:00",
};

export const bidFixture: BidState = {
  bid: {
    id: "BID-DEMO-001",
    title: "Managed Cybersecurity Monitoring and Response Services",
    agency: "Demo Government Agency",
    reference_number: "DGA/ICT/2026/017",
    closing_at: "2026-08-28T09:00:00",
    source_type: "SYNTHETIC",
    synthetic: true,
    fixture_id: "main-corrigendum",
  },
  company: {
    id: "COMPANY-DEMO-001",
    name: "NexusFort Technologies Pte. Ltd.",
    uen: "202612345N",
    industry: "Cybersecurity",
    employee_count: 8,
    annual_revenue: "S$4.8M",
  },
  interpretation: {
    mode: "DEMO_FALLBACK",
    label: "Demo fallback",
    model_id: null,
    source: "no_persisted_interpretation",
    event_id: null,
  },
  metrics: {
    operational_status: "FEASIBLE",
    previous_operational_status: null,
    critical_gates_verified: 8,
    critical_gates_total: 8,
    submission_coverage: 91,
    deadline_risk: "LOW",
  },
  calculations: {
    operational_feasibility: {
      status: "FEASIBLE",
      reason: "Every current mandatory requirement is satisfied.",
      precedence: ["BLOCKED", "UNCERTAIN", "RECOVERABLE", "FEASIBLE"],
      mandatory_total: 8,
      unresolved: [],
      persisted_value: "FEASIBLE",
      matches_persisted_value: true,
    },
    critical_gates: {
      verified: 8,
      total: 8,
      rule: "Only SATISFIED mandatory requirements are verified.",
      gates: [],
    },
    submission_coverage: {
      display_percent: 91,
      raw_percent: 90.5,
      formula: "0.50 × Requirement + 0.30 × Evidence + 0.20 × Tasks",
      rounding: "Nearest whole percent.",
      warning: "Preparation completeness is not a compliance score.",
      persisted_value: 91,
      matches_persisted_value: true,
      components: {
        requirements: {
          label: "Requirement Coverage",
          weight: 0.5,
          percent: 100,
          weighted_points: 50,
          completed_units: 24,
          total_units: 24,
          unit_label: "weighted units",
          rule: "Mandatory requirements have three units.",
        },
        evidence: {
          label: "Evidence Coverage",
          weight: 0.3,
          percent: 75,
          weighted_points: 22.5,
          completed_units: 9,
          total_units: 12,
          unit_label: "records",
          rule: "Verified records divided by all records.",
        },
        tasks: {
          label: "Task Coverage",
          weight: 0.2,
          percent: 90,
          weighted_points: 18,
          completed_units: 9,
          total_units: 10,
          unit_label: "tasks",
          rule: "Done tasks divided by all tasks.",
        },
      },
    },
    deadline_risk: {
      risk: "LOW",
      calculated_at: "2026-08-21T15:00:00",
      driver_task_id: null,
      driver_task_title: null,
      minimum_slack_hours: null,
      formula: "Minimum task slack.",
      thresholds: { LOW: "more than 48 hours" },
      persisted_value: "LOW",
      matches_persisted_value: true,
      tasks: [],
    },
  },
  requirements: [
    {
      id: "REQ-R17-V1",
      stable_key: "R17",
      version: 1,
      text: "Minimum 3 valid CISSP-certified engineers.",
      requirement_type: "MANPOWER",
      gate_type: "MANDATORY",
      assessment: "SATISFIED",
      assessment_reason: "Three complete evidence sets are verified.",
      assessment_method: "RULE",
      assessed_at: "2026-08-21T15:00:00",
      evidence_count: 3,
      evidence: [],
      source: {
        document: "Technical Specification.pdf",
        page: 17,
        section: "4.3",
        snippet: "Minimum 3 valid CISSP-certified engineers.",
      },
      history: [],
    },
  ],
  tasks: [],
  critical_actions: [],
  latest_change: null,
  impact_chain: [],
  recovery_candidate: null,
  portfolio_impact: null,
  activity_events: [],
  human_review: {
    required: true,
    approved: false,
    approved_by: null,
    approved_at: null,
  },
  disclaimer: "Final tender interpretation and submission remain supplier-controlled.",
};
