import type { BidState } from "../types/bid";

export const bidFixture: BidState = {
  bid: {
    id: "BID-DEMO-001",
    title: "Managed Cybersecurity Monitoring and Response Services",
    agency: "Demo Government Agency",
    reference_number: "DGA/ICT/2026/017",
    closing_at: "2026-08-28T09:00:00",
    source_type: "SYNTHETIC",
    synthetic: true,
    fixture_id: "main-corrigendum",
  },
  company: {
    id: "COMPANY-DEMO-001",
    name: "NexusFort Technologies Pte. Ltd.",
    uen: "202612345N",
    industry: "Cybersecurity",
    employee_count: 8,
    annual_revenue: "S$4.8M",
  },
  interpretation: {
    mode: "DEMO_FALLBACK",
    label: "Demo fallback",
    model_id: null,
    source: "no_persisted_interpretation",
    event_id: null,
  },
  metrics: {
    operational_status: "FEASIBLE",
    previous_operational_status: null,
    critical_gates_verified: 8,
    critical_gates_total: 8,
    submission_coverage: 91,
    deadline_risk: "LOW",
  },
  calculations: {
    operational_feasibility: {
      status: "FEASIBLE",
      reason: "Every current mandatory requirement is satisfied.",
      precedence: ["BLOCKED", "UNCERTAIN", "RECOVERABLE", "FEASIBLE"],
      mandatory_total: 8,
      unresolved: [],
      persisted_value: "FEASIBLE",
      matches_persisted_value: true,
    },
    critical_gates: {
      verified: 8,
      total: 8,
      rule: "Only SATISFIED mandatory requirements are verified.",
      gates: [],
    },
    submission_coverage: {
      display_percent: 91,
      raw_percent: 90.5,
      formula: "0.50 × Requirement + 0.30 × Evidence + 0.20 × Tasks",
      rounding: "Nearest whole percent.",
      warning: "Preparation completeness is not a compliance score.",
      persisted_value: 91,
      matches_persisted_value: true,
      components: {
        requirements: {
          label: "Requirement Coverage",
          weight: 0.5,
          percent: 100,
          weighted_points: 50,
          completed_units: 24,
          total_units: 24,
          unit_label: "weighted units",
          rule: "Mandatory requirements have three units.",
        },
        evidence: {
          label: "Evidence Coverage",
          weight: 0.3,
          percent: 75,
          weighted_points: 22.5,
          completed_units: 9,
          total_units: 12,
          unit_label: "records",
          rule: "Verified records divided by all records.",
        },
        tasks: {
          label: "Task Coverage",
          weight: 0.2,
          percent: 90,
          weighted_points: 18,
          completed_units: 9,
          total_units: 10,
          unit_label: "tasks",
          rule: "Done tasks divided by all tasks.",
        },
      },
    },
    deadline_risk: {
      risk: "LOW",
      calculated_at: "2026-08-21T15:00:00",
      driver_task_id: null,
      driver_task_title: null,
      minimum_slack_hours: null,
      formula: "Minimum task slack.",
      thresholds: { LOW: "more than 48 hours" },
      persisted_value: "LOW",
      matches_persisted_value: true,
      tasks: [],
    },
  },
  requirements: [
    {
      id: "REQ-R17-V1",
      stable_key: "R17",
      version: 1,
      text: "Minimum 3 valid CISSP-certified engineers.",
      requirement_type: "MANPOWER",
      gate_type: "MANDATORY",
      assessment: "SATISFIED",
      assessment_reason: "Three complete evidence sets are verified.",
      assessment_method: "RULE",
      assessed_at: "2026-08-21T15:00:00",
      evidence_count: 3,
      evidence: [],
      source: {
        document: "Technical Specification.pdf",
        page: 17,
        section: "4.3",
        snippet: "Minimum 3 valid CISSP-certified engineers.",
      },
      history: [],
    },
  ],
  tasks: [],
  critical_actions: [],
  latest_change: null,
  impact_chain: [],
  recovery_candidate: null,
  activity_events: [],
  human_review: {
    required: true,
    approved: false,
    approved_by: null,
    approved_at: null,
  },
  disclaimer: "Final tender interpretation and submission remain supplier-controlled.",
};
